### ISSUE TITLE
Road to v1 stable

### ISSUE THREAD

**Issue by ericvicenti** [react-community/react-navigation#723]
For the first release, lets focus on API sanity and stability, rather than adding every feature that people have requested.

- [ ] Navigate key for idempotent pushes https://github.com/react-community/react-navigation/issues/135
- [ ] Go back to a screen: https://github.com/react-community/react-navigation/issues/1213
- [x] Header bar overriding https://github.com/react-community/react-navigation/pull/1220
- [ ] Screen lifecycle hooks https://github.com/react-community/react-navigation/issues/51
- [x] Simplified Nav Options https://github.com/react-community/react-navigation/issues/722
- [x] Resetting non-deepest navigator https://github.com/react-community/react-navigation/issues/691
- [ ] Explore `<NavigationOptions />` for a less confusing configuration method
- [ ] Fix issues with drawer navigator - https://github.com/react-community/react-navigation/issues/374

After v1:

- [ ] Accessibility Review https://github.com/react-community/react-navigation/issues/58

Lets aim to reach stability by mid-April!

**Comment by chandu0101** [comment]
any chance to get this  https://github.com/react-community/react-navigation/issues/691 in v1 ..

**Comment by ericvicenti** [comment]
@chandu0101, yep, just added it! I'm still searching around for high-pri issues

**Comment by migueloller** [comment]
@ericvicenti is https://github.com/react-community/react-navigation/issues/175 a high priority for v1?

**Comment by jakecraige** [comment]
I'd second #175 / #124 being part of 1.0. There's a large amount of ceremony around having an individual screen within a `StackNavigator` present from the bottom up that seems like a fairly core feature that many would find useful.

**Comment by nihgwu** [comment]
@ericvicenti what about #271 debounce action reduce
and as I've said in #271, we shouldn't override custom **key**, or we can't find specific screen via **key** as it could be override, per #691 and NavigationActions.back('key')

**Comment by migueloller** [comment]
@nihgwu, I believe #135, which @ericvicenti included in the list above, would solve that problem.

**Comment by cychiuae** [comment]
I believe #527 is important too

**Comment by nihgwu** [comment]
@migueloller sorry I didn't notice that before

**Comment by nihgwu** [comment]
@cychiuae but #527 has been resolved, forget to close it though

**Comment by cychiuae** [comment]
@nihgwu someone said he still got the issue with master

**Comment by TomAtterton** [comment]
@ericvicenti  I've noticed you still haven't added [#175](https://github.com/react-community/react-navigation/issues/175) / [#124](https://github.com/react-community/react-navigation/issues/124) / [#690](https://github.com/react-community/react-navigation/issues/690)  / [#232](https://github.com/react-community/react-navigation/issues/232) The issue of controlling transitions of individual screens seems to be a high priority issue.

**Comment by getnashty** [comment]
+1 the need for #175.

**Comment by nehvaleem** [comment]
+1 need for #175

**Comment by nascode** [comment]
A better way to configure screen transitions is needed for react-navigation to be competitive with other solution.

+1 for #175

**Comment by aranda-adapptor** [comment]
Perhaps #802 (Ability to "replace" screens in the stack navigator) should be on this list?

**Comment by ragnorc** [comment]
+1 for #175

**Comment by lashae** [comment]
> ...
> Lets aim to reach stability by mid-April!

We are just one week away from mid-April and it seems that all of the referenced issues are still open. I guess mid-April deadline is not realistic so far. 

Is there any new ETA for the stable version?

**Comment by ericvicenti** [comment]
The most important thing right now is for us to focus on stability so that people's apps are production-ready.

I think #124 and #175 are important for the long-term success of the library, but these are invasive and risky changes. We are trying to stabilize the library, and these features would require us to rip it up. If you're interested in highly-customized animations, you can of course use [`Transitioner`](https://reactnavigation.org/docs/views/transitioner) directly, or you can find a third-party library that takes a navigation prop.

For those interested in an easy way to configure some screens as a modal and others as a card (#707 #770 #690 #232), you may find [this workaround handy](https://github.com/react-community/react-navigation/issues/707#issuecomment-293748852). I think it would break a lot of things if we tried to implement it differently. If anybody has ideas for a different implementation, feel free to open up a new issue and we can discuss. Maybe there is an easier way that I'm not seeing.

Replace functionality (#802) is also a pretty common request, and I think we could accomplish it by adding a key to the navigation action- you'd just pass the current key in order to replace. It seems that #271 would also get solved by #135.

@lashae, I won't make any more promises on timeline, but if you have any important fixes for your app, ping me and I'll help you merge them!

**Comment by charlle** [comment]
@ericvicenti The screen life cycle events proposed in (#51)[https://github.com/react-community/react-navigation/issues/51] are necessary to manage Scene updates on Back, to close and open web sockets / event listeners.  Are there proposed work arounds?

**Comment by ericvicenti** [comment]
@charlle, at the moment you can use controlled navigators, (see the redux example). When you explicitly provide the `navigation.state`, you can see when it changes and do things at that time. But I agree that #51 is very high-pri

**Comment by grabbou** [comment]
From my perspective, https://github.com/react-community/react-navigation/issues/88 would be great. I could work on it we can make it into next release candidate.

**Comment by charlle** [comment]
@ericvicenti Thanks for the response.  Just to clarify are you suggesting to have a HOC "watch" and compare `navigation.state` changes rather than have a triggered event at the component level?

**Comment by nonameolsson** [comment]
Looking good! We switched to `react-navigation` from `react-native-router-flux` in our company's first React Native app. Really looking forward to a stable version of `react-navigation`.  As a first version I think it contains enough features. And with those mentioned in this issue, it will be a great alternative for other routers.

Keep up the good work! ⭐️

**Comment by jamesisaac** [comment]
@ericvicenti I feel like something like #525 / #486 (Allow `TabBarBottom` accept `onTabPress` callback) is pretty crucial.  A large number of production apps which use bottom tabs have some custom action when the currently active tab is pressed again (e.g. reset the stack, scroll to top, etc).  Feels like quite a limitation that this isn't supported.

**Comment by DaleJefferson** [comment]
Animated replace is an important issue for us. #351

**Comment by grabbou** [comment]
We are quite settled on the initial list of features to support in v1 release. If you'd like to suggest more improvements, feel free to visit #1263 where we are discussing things to go into second stable release (namely v2)

**Comment by boliveira** [comment]
I think #706 should be in the list for v1.

**Comment by MovingGifts** [comment]
Almost 2 months in past the mid-April v1 estimate. Any status updates?

**Comment by luco** [comment]
+1 for #707 . I think adding a `mode` for each scene it's a must.

**Comment by timwangdev** [comment]
Expecting release a new beta version for all the issues are fixed in master.

**Comment by rpopovici** [comment]
I opened some PRs. Is anyone checking this stuff?
- idempotent pushes https://github.com/react-community/react-navigation/pull/2334
- queued action dispatch and fixed queued transitions in Transitioner https://github.com/react-community/react-navigation/pull/2400
- some fixes to the Drawer menu https://github.com/react-community/react-navigation/pull/2294
- fix reset action in stack navigator https://github.com/react-community/react-navigation/pull/2292

**Comment by spencercarli** [comment]
@rpopovici working on it - project went quiet for a while but we're playing catch up and trying to get things sorted out. Appreciate all the PRs you've opened - we'll get to them!

**Comment by rabrenio** [comment]
Please include more tab for IOS. It should have more tab if the items cant fit the horizontal space. Thanks.

**Comment by dantman** [comment]
@rabrenio Could you add a feature request for that instead of just a comment in the v1 issue.

**Comment by rabrenio** [comment]
@dantman yes its an issue thats why i requested it to be included as a new feature.

**Comment by kelset** [comment]
Closing this issue in favour of #2585.
